//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.EMAIL_VERIFICATION = new HashSet<EMAIL_VERIFICATION>();
            this.PASSWORD_RESET_TOKEN = new HashSet<PASSWORD_RESET_TOKEN>();
        }
    
        public int account_id { get; set; }
        public int player_id { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public bool is_email_verified { get; set; }
        public Nullable<System.DateTime> email_verified_at { get; set; }
        public string account_status { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_VERIFICATION> EMAIL_VERIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASSWORD_RESET_TOKEN> PASSWORD_RESET_TOKEN { get; set; }
    }
}
