//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY_TRANSLATION
    {
        public int category_translation_id { get; set; }
        public int category_id { get; set; }
        public string language_code { get; set; }
        public string name { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
    }
}
