//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATCH()
        {
            this.MATCH_GUESS = new HashSet<MATCH_GUESS>();
            this.SCORE_MOVEMENT = new HashSet<SCORE_MOVEMENT>();
        }
    
        public int match_id { get; set; }
        public int host_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public int word_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> joined_at { get; set; }
        public Nullable<System.DateTime> started_at { get; set; }
        public Nullable<System.DateTime> finished_at { get; set; }
        public string match_status { get; set; }
        public Nullable<int> winner_id { get; set; }
        public Nullable<int> penalized_user_id { get; set; }
        public int failed_attempts { get; set; }
        public int max_attempts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATCH_GUESS> MATCH_GUESS { get; set; }
        public virtual PLAYER PLAYER { get; set; }
        public virtual PLAYER PLAYER1 { get; set; }
        public virtual PLAYER PLAYER2 { get; set; }
        public virtual PLAYER PLAYER3 { get; set; }
        public virtual WORD WORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCORE_MOVEMENT> SCORE_MOVEMENT { get; set; }
    }
}
