//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_CATEGORY_VOTE
    {
        public int match_category_vote_id { get; set; }
        public int match_id { get; set; }
        public int player_id { get; set; }
        public int category_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual MATCH MATCH { get; set; }
        public virtual PLAYER PLAYER { get; set; }
    }
}
