//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_GUESS
    {
        public int guess_id { get; set; }
        public int match_id { get; set; }
        public int guessed_by_id { get; set; }
        public string letter { get; set; }
        public bool is_correct { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
        public virtual MATCH MATCH { get; set; }
    }
}
