//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD_RESET_TOKEN
    {
        public int password_reset_token_id { get; set; }
        public int account_id { get; set; }
        public string reset_code_hash { get; set; }
        public System.DateTime expires_at { get; set; }
        public Nullable<System.DateTime> used_at { get; set; }
        public int attempts { get; set; }
        public bool is_used { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
