//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORD_TRANSLATION
    {
        public int word_translation_id { get; set; }
        public int word_id { get; set; }
        public string language_code { get; set; }
        public string word_text { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual WORD WORD { get; set; }
    }
}
